""" 1st sep 2022 thursday 
string methods  """
# print(dir(str))
# a=input()
# print(a.upper())
# print(a.lower())
# print(a.isupper())
# print(a.islower())
# print(a.swapcase())
# print(a.capitalize())
# print(a.title())
# # print(a.istitle())
# print(len(a))
# print(a.isspace())
# print(''.isspace())   
# print(' '.isspace())   
# print(' p'.isspace())   
# print('    '.isspace())   
# print('hi'.isalnum())
# print('4'.isalnum())
# # print('  '.isalnum())
# # print('hi5_'.isalnum())
# print('a'.isalpha())
# print('A'.isalpha())
# print(' '.isalpha())
# print('4'.isalpha())
# print('jagadish'.isalpha())
#  print(a.count('j'))

